### PR TITLE
avoid out of bounds in _frequencies!

### LINKED ISSUE #18: Binning problem in mutualinformation?
Very rarely this can happen:
```julia
using DynamicalSystems
ds = Systems.gissinger(ones(3)) # 3D continuous chaotic system, also shown in orbit diagrams tutorial
dt = 0.05
data = trajectory(ds, 1000.0, dt = dt)
s = data[:, 1]

τ = estimate_delay(s, "mi_min", 0:1:400)
```
```
ERROR: BoundsError: attempt to access 98-element Array{Float64,1} at index [99]
Stacktrace:
 [1] getindex at .\array.jl:729 [inlined]
 [2] _frequencies!(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}) at C:\Users\datseris\.julia\dev\DelayEmbeddings\src\estimate_delay.jl:269
 [3] _mutualinfo!(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Int64,1}, ::Array{Float64,1}) at C:\Users\datseris\.julia\dev\DelayEmbeddings\src\estimate_delay.jl:240
 [4] #mutualinformation#56(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Array{Float64,1}, ::StepRange{Int64,Int64}) at C:\Users\datseris\.julia\dev\DelayEmbeddings\src\estimate_delay.jl:207
 [5] mutualinformation at C:\Users\datseris\.julia\dev\DelayEmbeddings\src\estimate_delay.jl:197 [inlined]
 [6] #estimate_delay#39(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Array{Float64,1}, ::String, ::StepRange{Int64,Int64}) at C:\Users\datseris\.julia\dev\DelayEmbeddings\src\estimate_delay.jl:50
 [7] estimate_delay(::Array{Float64,1}, ::String, ::StepRange{Int64,Int64}) at C:\Users\datseris\.julia\dev\DelayEmbeddings\src\estimate_delay.jl:33
 [8] top-level scope at none:0
```
Increasing the total integration time seems to fix it, but I do not know where the bug is coming from.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/69808478-binning-problem-in-mutualinformation?utm_campaign=plugin&utm_content=tracker%2F115474986&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F115474986&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by heliosdrm**
Closes #18 (I hope).

### CODE REVIEW

**Comment by heliosdrm** [comment]
Oh my! What's happening here? The test does not fail in my machine. (Although it does issue the warning: "Did not encounter a minimum, returning last `τ`")

**Comment by Datseris** [comment]
@heliosdrm I've added a commit here that uses the previous solver, `Vern9` for the `trajectory` calls. I think this will fix the unreasonable failures you were seeing. 

I am so sorry for this confusion. I was testing everything locally, but forgot to test `DelayEmbeddings`. (It was of course a big mistake to assume it wouldn't be affected)

**Comment by Datseris** [comment]
Hm, something else is wrong _besides_ the new solver. In my latest commit I use absolutely identical solver as in `DynamicalSystemsBase 1.1`. However, for the mutual information estimation of the lorentz system, line 30 of the test file `R_delay.jl`, I get the error:
```
  Expression: 1.15 ≤ estimate_delay(x, "mi_min", 1:2:500) * dt ≤ 1.6
   Evaluated: 1.15 ≤ 1.02 ≤ 1.6
```

I wonder why this happens, even though I am now certainly using (effectively) version 1.1 of DynamicalSystemsBase...?

**Comment by heliosdrm** [comment]
I'm afraid that I can help much here, since I don't know the internals of DynamicalSystems.

I just can tell that locally, checking out DynamicalSystems v.1.1.1 makes the test pass again, whatever version/branch of DelayEmbeddings I am testing. So I'd say that this is not exactly reproducing the algorithm of that version...

**Comment by Datseris** [comment]
>  So I'd say that this is not exactly reproducing the algorithm of that version...

Yes you are correct. I will investigate further tomorrow morning....

**Comment by heliosdrm** [comment]
Why the pull request passes the test, but the latest commit does not, I can't tell :astonished: 

In my machine it does pass with this latest version and the DynamicalSystems 1.2.2, for what is worth.

**Comment by heliosdrm** [comment]
Ok, and It seems everything passes in CI as well

**Comment by Datseris** [comment]
Yeah!!! Something crazy must has happened in a CI tests, because it was passing locally for me as well!

So, do we merge?

**Comment by heliosdrm** [comment]
Yes, I think

**Pull request merged**
