### PR TITLE
Bugfix hcat lagged

### PR DESCRIPTION
**Pull request by hkraemer**
Here is a minor bugfix for the function `hcat_lagged_values`. The former version always reduced the length of the output Dataset by the given delay value `τ`. Now it is just reducing the size according to the available data in `s`. @Datseris , you made it right in the implementation of `genembed` though.

### CODE REVIEW

**Comment by Datseris** [comment]
Alright, thanks. We need to add a basic test for this function, given that we already made a mistake with it once. I don't think `hcat_lagged_values` is used anywhere in the tests.

**Comment by hkraemer** [comment]
No it is not. I will incorporate it when adjusting the tests to the new PECUZAL version. This bugfix, however, might break the tests of the actual PECUZAL tests...

**Comment by Datseris** [comment]
You can do both in this PR.

**Comment by Datseris** [comment]
Hi @hkraemer , please increment minor version in Project.toml, and also add an entry in CHANGELOG.md with a one-sentence description of changes users should be aware of. Then I'll merge and tag a new version.

**Pull request merged**
