### PR TITLE
Improve is stochastic clause for automated TDE

### PR DESCRIPTION
**Pull request by Datseris**
@hkraemer

### CODE REVIEW

**Comment by Datseris** [comment]
At the moment we just print a statement "Embedding not achieved." Shouldn't we error instead?

**Comment by hkraemer** [comment]
Jepp, we should return the time series, which has been put in, in this case and leave the message, I suggest.

**Comment by Datseris** [comment]
I'm asking whether the function should **error** instead of simply **printing** a message.

**Comment by hkraemer** [comment]
I suggest to let it print that message and return the single time series. Might be more handy in a loop-evaluation

**Pull request merged**
